spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    placeholders:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD_HASH: '${ADMIN_PASSWORD_HASH}'

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: ${JWT_ACCESS_EXPIRATION_TIME} # 15 minutes
      refresh-token-expiration: ${JWT_REFRESH_EXPIRATION_TIME} # 7 days
