-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 09:58:20 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`authors` (
                                                   `created_at` DATETIME(6) NOT NULL,
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `first_name` VARCHAR(50) NULL DEFAULT NULL,
    `last_name` VARCHAR(50) NULL DEFAULT NULL,
    `full_name` VARCHAR(100) NOT NULL,
    `type` ENUM('CORPORATION', 'INDIVIDUAL') NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books` (
                                                 `available_copies` INT NOT NULL,
                                                 `total_copies` INT NOT NULL,
                                                 `created_at` DATETIME(6) NOT NULL,
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `version` BIGINT NULL DEFAULT NULL,
    `isbn` VARCHAR(20) NULL DEFAULT NULL,
    `title` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `UKkibbepcitr0a3cpk3rfr7nihn` (`isbn` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_authors` (
                                                        `author_id` BIGINT NOT NULL,
                                                        `book_id` BIGINT NOT NULL,
                                                        PRIMARY KEY (`author_id`, `book_id`),
    INDEX `FKbhqtkv2cndf10uhtknaqbyo0a` (`book_id` ASC) VISIBLE,
    CONSTRAINT `FKbhqtkv2cndf10uhtknaqbyo0a`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`books` (`id`),
    CONSTRAINT `FKo86065vktj3hy1m7syr9cn7va`
    FOREIGN KEY (`author_id`)
    REFERENCES `library`.`authors` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`categories` (
                                                      `created_at` DATETIME(6) NOT NULL,
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `UKt8o6pivur7nn124jehx7cygw5` (`name` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`book_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_categories` (
                                                           `book_id` BIGINT NOT NULL,
                                                           `category_id` BIGINT NOT NULL,
                                                           PRIMARY KEY (`book_id`, `category_id`),
    INDEX `FKrg2xlmc92mm2y5b1wmhd2g0y0` (`category_id` ASC) VISIBLE,
    CONSTRAINT `FK3k3ahp5vqlgmrr9swqqprmbxy`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`books` (`id`),
    CONSTRAINT `FKrg2xlmc92mm2y5b1wmhd2g0y0`
    FOREIGN KEY (`category_id`)
    REFERENCES `library`.`categories` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`users` (
                                                 `created_at` DATETIME(6) NOT NULL,
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `last_login` DATETIME(6) NULL DEFAULT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `username` VARCHAR(30) NOT NULL,
    `first_name` VARCHAR(50) NOT NULL,
    `last_name` VARCHAR(50) NOT NULL,
    `password` VARCHAR(128) NOT NULL,
    `role` ENUM('LIBRARIAN', 'MEMBER') NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`librarians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`librarians` (
                                                      `id` BIGINT NOT NULL,
                                                      `position` ENUM('ASSISTANT_LIBRARIAN', 'HEAD_LIBRARIAN') NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FKb05hx9rpc8sh3s04s0trryqsg`
    FOREIGN KEY (`id`)
    REFERENCES `library`.`users` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`members` (
                                                   `id` BIGINT NOT NULL,
                                                   `membership_number` VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FK8xc8ex06k91fyx0v7hqafk62u`
    FOREIGN KEY (`id`)
    REFERENCES `library`.`users` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`loans` (
                                                 `due_date` DATE NOT NULL,
                                                 `loan_date` DATE NOT NULL,
                                                 `return_date` DATE NULL DEFAULT NULL,
                                                 `book_id` BIGINT NOT NULL,
                                                 `created_at` DATETIME(6) NOT NULL,
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `librarian_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    `updated_at` DATETIME(6) NULL DEFAULT NULL,
    `status` ENUM('BORROWED', 'OVERDUE', 'RETURNED') NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `FKokwvlrv6o4i4h3le3bwhe6kie` (`book_id` ASC) VISIBLE,
    INDEX `FKdccbfjbfs4itsg1xb8obq41g8` (`librarian_id` ASC) VISIBLE,
    INDEX `FKcx90n1minpb22v3jw4ojinqm` (`member_id` ASC) VISIBLE,
    CONSTRAINT `FKcx90n1minpb22v3jw4ojinqm`
    FOREIGN KEY (`member_id`)
    REFERENCES `library`.`members` (`id`),
    CONSTRAINT `FKdccbfjbfs4itsg1xb8obq41g8`
    FOREIGN KEY (`librarian_id`)
    REFERENCES `library`.`librarians` (`id`),
    CONSTRAINT `FKokwvlrv6o4i4h3le3bwhe6kie`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`books` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`tokens` (
                                                  `expired` BIT(1) NOT NULL,
    `revoked` BIT(1) NOT NULL,
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `token` VARCHAR(255) NOT NULL,
    `token_type` ENUM('BEARER') NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `UKna3v9f8s7ucnj16tylrs822qj` (`token` ASC) VISIBLE,
    INDEX `FK2dylsfo39lgjyqml2tbe0b0ss` (`user_id` ASC) VISIBLE,
    CONSTRAINT `FK2dylsfo39lgjyqml2tbe0b0ss`
    FOREIGN KEY (`user_id`)
    REFERENCES `library`.`users` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
